<a href="https://colab.research.google.com/github/pranjalchaubey/Deep-Learning-Notes/blob/master/Kevin's%20Data%20Science%20Class%20Notes/Kevin_Class_1_and_2_Code_with_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import sklearn
sklearn.__version__

'0.22.2.post1'

# Part 1

In [0]:
import pandas as pd 
df = pd.read_csv('http://bit.ly/kaggletrain', nrows=10)

In [0]:
df

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[10 rows x 12 columns]

In [0]:
df.info

<bound method DataFrame.info of    PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[10 rows x 12 columns]>

In [0]:
X = df[['Parch', 'Fare']]
X

Parch     Fare
0      0   7.2500
1      0  71.2833
2      0   7.9250
3      0  53.1000
4      0   8.0500
5      0   8.4583
6      0  51.8625
7      1  21.0750
8      2  11.1333
9      0  30.0708

In [0]:
y = df['Survived']
y

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: Survived, dtype: int64

In [0]:
y.shape

(10,)

In [0]:
from sklearn.linear_model import LogisticRegression

In [0]:
logreg = LogisticRegression(solver='liblinear', random_state=1)

In [0]:
from sklearn.model_selection import cross_val_score
cross_val_score(logreg, X, y, cv=3, scoring='accuracy').mean()

0.6944444444444443

In [0]:
logreg.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
df_new = pd.read_csv('http://bit.ly/kaggletest', nrows=10)

In [0]:
df_new

PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S
5          897       3  ...   NaN        S
6          898       3  ...   NaN        Q
7          899       2  ...   NaN        S
8          900       3  ...   NaN        C
9          901       3  ...   NaN        S

[10 rows x 11 columns]

In [0]:
X_new = df_new[['Parch', 'Fare']]
X_new

Parch     Fare
0      0   7.8292
1      0   7.0000
2      0   9.6875
3      0   8.6625
4      1  12.2875
5      0   9.2250
6      0   7.6292
7      1  29.0000
8      0   7.2292
9      0  24.1500

# Part 2

In [0]:
df

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[10 rows x 12 columns]

In [0]:
from sklearn.preprocessing import OneHotEncoder 
ohe = OneHotEncoder(sparse=False) # Normally you dont see the sparse matrix. \
                                    # set sparse = True in real life 
ohe.fit_transform(df[['Embarked']]) # Two brackets tell sklearn that this is a 
                                    # FEATURE (column), not a row (a collection
                                    # of features). 

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [0]:
# fit - learns from the data
# transform - uses what it learned from fit 
# fit_transform is a transformer
# it learns and then transforms 
# fit_transform - does both fitting and transform 
# if using both on a single dataset, use fit_transform instead of 
# fit and transform individually. 

In [0]:
ohe.categories_ # A trailing underscore_ means it was learned during the 'fit'
                # step

[array(['C', 'Q', 'S'], dtype=object)]

In [0]:
df[['Embarked']]

Embarked
0        S
1        C
2        S
3        S
4        S
5        Q
6        S
7        S
8        S
9        C

In [0]:
ohe.fit_transform(df[['Embarked', 'Sex']])

array([[0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.]])

In [0]:
df[['Sex']]

Sex
0    male
1  female
2  female
3  female
4    male
5    male
6    male
7    male
8  female
9  female

# Part 3

In [0]:
cols = ['Parch', 'Fare', 'Embarked', 'Sex']

In [0]:
X = df[cols]
X

Parch     Fare Embarked     Sex
0      0   7.2500        S    male
1      0  71.2833        C  female
2      0   7.9250        S  female
3      0  53.1000        S  female
4      0   8.0500        S    male
5      0   8.4583        Q    male
6      0  51.8625        S    male
7      1  21.0750        S    male
8      2  11.1333        S  female
9      0  30.0708        C  female

In [0]:
ohe = OneHotEncoder()

In [0]:
from sklearn.compose import make_column_transformer

In [0]:
ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']), # ohe is applied to Embarked and Sex
    remainder='passthrough')    # remainder cols are 'passedthrough'

In [0]:
ct.fit_transform(X)

array([[ 0.    ,  0.    ,  1.    ,  0.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    , 71.2833],
       [ 0.    ,  0.    ,  1.    ,  1.    ,  0.    ,  0.    ,  7.925 ],
       [ 0.    ,  0.    ,  1.    ,  1.    ,  0.    ,  0.    , 53.1   ],
       [ 0.    ,  0.    ,  1.    ,  0.    ,  1.    ,  0.    ,  8.05  ],
       [ 0.    ,  1.    ,  0.    ,  0.    ,  1.    ,  0.    ,  8.4583],
       [ 0.    ,  0.    ,  1.    ,  0.    ,  1.    ,  0.    , 51.8625],
       [ 0.    ,  0.    ,  1.    ,  0.    ,  1.    ,  1.    , 21.075 ],
       [ 0.    ,  0.    ,  1.    ,  1.    ,  0.    ,  2.    , 11.1333],
       [ 1.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    , 30.0708]])

In [0]:
from sklearn.pipeline import make_pipeline 
pipe = make_pipeline(ct, logreg) # Two step pipeline 

In [0]:
pipe.fit(X, y)
# X 4 col goes to ct 
# ct turns it into 7 cols 
# this is sent to logreg 
# logreg then applies the logisticregressoin 

# pipe.fit modifies the pipe object in-place, so we dont have to 
# assign it to a variable

# pipeline can end in a model or a transform. 
# for pipelines that end in a transform, we can use fit_transform()

# You can cross validate a pipeline, 
# You DO NOT include cross validation inside a pipeline. 

Pipeline(memory=None,
         steps=[('columntransformer',
                 ColumnTransformer(n_jobs=None, remainder='passthrough',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories='auto',
                                                                drop=None,
                                                                dtype=<class 'numpy.float64'>,
                                                                handle_unknown='error',
                                                                sparse=True),
                                                  ['Embarked', 'Sex'])],
                                   verbose=False)),
                ('logisticregression',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                         

In [0]:
logreg.fit(ct.fit_transform(X), y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
pipe.named_steps.logisticregression.coef_ # inspect a pipeline using named_steps
                                          # 7 coeffs because there were 7 features 

array([[ 0.26491287, -0.19848033, -0.22907928,  1.0075062 , -1.17015293,
         0.20056557,  0.01597307]])

In [0]:
X_new = df_new[cols]
X_new

Parch     Fare Embarked     Sex
0      0   7.8292        Q    male
1      0   7.0000        S  female
2      0   9.6875        Q    male
3      0   8.6625        S    male
4      1  12.2875        S  female
5      0   9.2250        S    male
6      0   7.6292        Q  female
7      1  29.0000        S    male
8      0   7.2292        C  female
9      0  24.1500        S    male

In [0]:
pipe.predict(X_new) # did not run ct.fit_transform
                    # only ct.transform()
                    # apply the encodings it learned during fit 
                    # to apply on the test set

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [0]:
logreg.predict(ct.transform(X_new)) # outputs 1 prediction for EVERY ROW

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

# Recap 

http://bit.ly/basic-pipeline

In [0]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [0]:
cols = ['Parch', 'Fare', 'Embarked', 'Sex']

In [0]:
df = pd.read_csv('http://bit.ly/kaggletrain', nrows=10)
X = df[cols]
y = df['Survived']

In [0]:
df_new = pd.read_csv('http://bit.ly/kaggletest', nrows=10)
X_new = df_new[cols]

In [0]:
ohe = OneHotEncoder()

In [0]:
ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']),
    remainder='passthrough')

In [0]:
logreg = LogisticRegression(solver='liblinear', random_state=1)

In [0]:
pipe = make_pipeline(ct, logreg)
pipe.fit(X, y)
pipe.predict(X_new)

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

# Part 4 


In [0]:
df

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[10 rows x 12 columns]

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
dtm = vect.fit_transform(df['Name']) # CV wants a 1D object not a 2D hence 
                                     # single brackets 
dtm # Document Term Matrix - Sparse Matrix

<10x40 sparse matrix of type '<class 'numpy.int64'>'
	with 46 stored elements in Compressed Sparse Row format>

In [0]:
print(vect.get_feature_names()) # Think of them as col headings 
                                # Ignored words with less than a 2 letters 

['achem', 'adele', 'allen', 'berg', 'bradley', 'braund', 'briggs', 'cumings', 'elisabeth', 'florence', 'futrelle', 'gosta', 'harris', 'heath', 'heikkinen', 'henry', 'jacques', 'james', 'john', 'johnson', 'laina', 'leonard', 'lily', 'master', 'may', 'mccarthy', 'miss', 'moran', 'mr', 'mrs', 'nasser', 'nicholas', 'oscar', 'owen', 'palsson', 'peel', 'thayer', 'timothy', 'vilhelmina', 'william']


In [0]:
pd.DataFrame(dtm.toarray(), columns=vect.get_feature_names()) # 10 x 40 matrix 
                                                              # CV counts how many 
                                                              # times a particular 
                                                              # 'feature' or word
                                                              # appears 
                                                              # This is also a BOW
                                                              # representation 
                                                              # of text
# Docs are the rows and terms are the cols -> Document Term Matrix   

# With Text Data - DONT OVERTHINK IT.                                 

achem  adele  allen  berg  ...  thayer  timothy  vilhelmina  william
0      0      0      0     0  ...       0        0           0        0
1      0      0      0     0  ...       1        0           0        0
2      0      0      0     0  ...       0        0           0        0
3      0      0      0     0  ...       0        0           0        0
4      0      0      1     0  ...       0        0           0        1
5      0      0      0     0  ...       0        0           0        0
6      0      0      0     0  ...       0        1           0        0
7      0      0      0     0  ...       0        0           0        0
8      0      0      0     1  ...       0        0           1        0
9      1      1      0     0  ...       0        0           0        0

[10 rows x 40 columns]

In [0]:
cols = ['Parch', 'Fare', 'Embarked', 'Sex', 'Name']
X = df[cols]
X

Parch     Fare  ...     Sex                                               Name
0      0   7.2500  ...    male                            Braund, Mr. Owen Harris
1      0  71.2833  ...  female  Cumings, Mrs. John Bradley (Florence Briggs Th...
2      0   7.9250  ...  female                             Heikkinen, Miss. Laina
3      0  53.1000  ...  female       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      0   8.0500  ...    male                           Allen, Mr. William Henry
5      0   8.4583  ...    male                                   Moran, Mr. James
6      0  51.8625  ...    male                            McCarthy, Mr. Timothy J
7      1  21.0750  ...    male                     Palsson, Master. Gosta Leonard
8      2  11.1333  ...  female  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9      0  30.0708  ...  female                Nasser, Mrs. Nicholas (Adele Achem)

[10 rows x 5 columns]

In [0]:
ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']),
    (vect, 'Name'), # CV expects 1D inputs, hence not ['Name']
    remainder='passthrough')

In [0]:
ct.fit_transform(X)

<10x47 sparse matrix of type '<class 'numpy.float64'>'
	with 78 stored elements in Compressed Sparse Row format>

In [0]:
pipe = make_pipeline(ct, logreg) # remaking the pipe object, hence the assignment
pipe.fit(X, y);
# pipe.fit(X, y); adding semicolon suprresses output in Jupyter Notebook

In [0]:
pipe.named_steps

{'columntransformer': ColumnTransformer(n_jobs=None, remainder='passthrough', sparse_threshold=0.3,
                   transformer_weights=None,
                   transformers=[('onehotencoder',
                                  OneHotEncoder(categories='auto', drop=None,
                                                dtype=<class 'numpy.float64'>,
                                                handle_unknown='error',
                                                sparse=True),
                                  ['Embarked', 'Sex']),
                                 ('countvectorizer',
                                  CountVectorizer(analyzer='word', binary=False,
                                                  decode_error='strict',
                                                  dtype=<class 'numpy.int64'>,
                                                  encoding='utf-8',
                                                  input='content',
                                    

In [0]:
X_new = df_new[cols]
pipe.predict(X_new)

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [0]:
# Pipeline Type 1 
# tranformer, tranformer, tranformer, tranformer, model
# Pipeline Type 2 
# tranformer, tranformer, tranformer, tranformer, tranformer

# Part 5

In [0]:
df

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[10 rows x 12 columns]

In [0]:
cols = ['Parch', 'Fare', 'Embarked', 'Sex', 'Name', 'Age']

In [0]:
X = df[cols]
X

Parch     Fare  ...                                               Name   Age
0      0   7.2500  ...                            Braund, Mr. Owen Harris  22.0
1      0  71.2833  ...  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2      0   7.9250  ...                             Heikkinen, Miss. Laina  26.0
3      0  53.1000  ...       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4      0   8.0500  ...                           Allen, Mr. William Henry  35.0
5      0   8.4583  ...                                   Moran, Mr. James   NaN
6      0  51.8625  ...                            McCarthy, Mr. Timothy J  54.0
7      1  21.0750  ...                     Palsson, Master. Gosta Leonard   2.0
8      2  11.1333  ...  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9      0  30.0708  ...                Nasser, Mrs. Nicholas (Adele Achem)  14.0

[10 rows x 6 columns]

In [0]:
# pipe.fit(X, y)

# Model can use and handle NaN and missing values.....which model? 

In [0]:
# option to handle missing values 
# 1. just drop - X.dropna()
# good option under 2 condts 
#  a. dropping very little data 
#  b. NaNs are randomly distributed 
# 2. Drop the whole cols - X.dropna(axis='columns') - just DONT. 
# 3. Impute missing values - can be a course on its own! - You're MAKING up data

In [0]:
from sklearn.impute import SimpleImputer 

imp = SimpleImputer()
imp.fit_transform(df[['Age']])  # by default fills the missing cols with the 
                                # mean (median and mode are also an option)

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [28.11111111],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ]])

In [0]:
imp.statistics_

array([28.11111111])

In [0]:
ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']),
    (vect, 'Name'), # CV expects 1D inputs, hence not ['Name']
    (imp, ['Age']),
    remainder='passthrough')
ct.fit_transform(X)

<10x48 sparse matrix of type '<class 'numpy.float64'>'
	with 88 stored elements in Compressed Sparse Row format>

In [0]:
pipe = make_pipeline(ct, logreg)
pipe.fit(X, y)
pipe.named_steps

{'columntransformer': ColumnTransformer(n_jobs=None, remainder='passthrough', sparse_threshold=0.3,
                   transformer_weights=None,
                   transformers=[('onehotencoder',
                                  OneHotEncoder(categories='auto', drop=None,
                                                dtype=<class 'numpy.float64'>,
                                                handle_unknown='error',
                                                sparse=True),
                                  ['Embarked', 'Sex']),
                                 ('countvectorizer',
                                  CountVectorizer(analyzer='word', binary=False,
                                                  decode_error='strict',
                                                  dtype=...
                                                  input='content',
                                                  lowercase=True, max_df=1.0,
                                             

In [0]:
X_new = df_new[cols]
pipe.predict(X_new)
# No imputation if X_new does not have any missing data in 'Age'
# if X_new has missing values in 'Age' col, value that gets imputed is the 
# mean of 'age' in X and NOT the mean of 'Age' in X_new

# You're only allowed to learn from training data 
# and then apply on training and testing
# Imputer learns the values from the Training data, NOT THE TESTING DATA. 

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [0]:
# Predictions are made 1 row at a time - Conceptually 
# if a row in X_new has a missing value in Age, it is going to impute a
# value that it learned from X

In [0]:
# When imputing missing values - we can create a representation for all the 
#                                missing values 
imp_indicator = SimpleImputer(add_indicator=True)
imp_indicator.fit_transform(X[['Age']])
# Sometimes MISSINGNESS of a value can be a good indicator/feature in itself. 

array([[22.        ,  0.        ],
       [38.        ,  0.        ],
       [26.        ,  0.        ],
       [35.        ,  0.        ],
       [35.        ,  0.        ],
       [28.11111111,  1.        ],
       [54.        ,  0.        ],
       [ 2.        ,  0.        ],
       [27.        ,  0.        ],
       [14.        ,  0.        ]])

In [0]:
# Some other types of imputers that might give better results 
# Iterative Imputer 

# Part 6 

In [0]:
df = pd.read_csv('http://bit.ly/kaggletrain')
df.shape

(891, 12)

In [0]:
df_new = pd.read_csv('http://bit.ly/kaggletest')
df_new.shape

(418, 11)

In [0]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [0]:
df_new.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [0]:
# Embarked missing in training set 
# Fare missing vals in Testing Set 

In [0]:
X = df[cols]
y = df['Survived']

In [0]:
ct = make_column_transformer(
    (ohe, ['Embarked', 'Sex']),
    (vect, 'Name'), # CV expects 1D inputs, hence not ['Name']
    (imp, ['Age']),
    remainder='passthrough')
ct.fit_transform(X) # embarked has missing values, hence the error! 

ValueError: ignored

In [0]:
# Solution - Impute missing values from embarked before one hot encoding it 
# Use Mode or a Constant value of choice 
imp_constant = SimpleImputer(strategy='constant', fill_value='missing')
# The imputer is going to FILL IN 'missing' for 'NaN'. It will become a 
# 4th column during OHE. 
# Recommended by 'Researchers'.

In [0]:
imp_ohe = make_pipeline(imp_constant, ohe) # TRANSFORMER ONLY PIPELINE - Optimus Prime Loves it
imp_ohe.fit_transform(X[['Embarked']])

<891x4 sparse matrix of type '<class 'numpy.float64'>'
	with 891 stored elements in Compressed Sparse Row format>

In [0]:
ohe.fit_transform(imp_constant.fit_transform(X[['Embarked']]))

<891x4 sparse matrix of type '<class 'numpy.float64'>'
	with 891 stored elements in Compressed Sparse Row format>

In [0]:
# All pipeline steps OTHER THAN THE FINAL STEP must be a transformer. 
# The Final Step CAN be a Transformer or a Model - The Two types of pipelines

# Embarked missing in training set 
ct = make_column_transformer(
    (imp_ohe, ['Embarked', 'Sex']), # Pipeline that ACTS as a Transformer
    (vect, 'Name'), # CV expects 1D inputs, hence not ['Name']
    (imp, ['Age']),
    remainder='passthrough')

In [0]:
ct.fit_transform(X)

<891x1518 sparse matrix of type '<class 'numpy.float64'>'
	with 7328 stored elements in Compressed Sparse Row format>

In [0]:
# Fare missing vals in Testing Set 
ct = make_column_transformer(
    (imp_ohe, ['Embarked', 'Sex']), # Pipeline that ACTS as a Transformer
    (vect, 'Name'), # CV expects 1D inputs, hence not ['Name']
    (imp, ['Age', 'Fare']), # Learn the mean value of Fare during train, apply on test later
    remainder='passthrough')
ct.fit_transform(X)

<891x1518 sparse matrix of type '<class 'numpy.float64'>'
	with 7328 stored elements in Compressed Sparse Row format>

In [0]:
pipe = make_pipeline(ct, logreg)
pipe.fit(X, y);

In [0]:
X_new = df_new[cols]
pipe.predict(X_new)

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [0]:
ct.named_transformers_.simpleimputer.statistics_

array([29.69911765, 32.20420797])

In [0]:
ct.named_transformers_.pipeline.named_steps.simpleimputer.statistics_

array(['missing', 'missing'], dtype=object)

# Recap  

http://bit.ly/complex-pipeline

In [0]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [0]:
cols = ['Parch', 'Fare', 'Embarked', 'Sex', 'Name', 'Age']

In [0]:
df = pd.read_csv('http://bit.ly/kaggletrain')
X = df[cols]
y = df['Survived']

In [0]:
df_new = pd.read_csv('http://bit.ly/kaggletest')
X_new = df_new[cols]

In [0]:
imp_constant = SimpleImputer(strategy='constant', fill_value='missing')
ohe = OneHotEncoder()

In [0]:
imp_ohe = make_pipeline(imp_constant, ohe)
vect = CountVectorizer()
imp = SimpleImputer()

In [0]:
ct = make_column_transformer(
    (imp_ohe, ['Embarked', 'Sex']),
    (vect, 'Name'),
    (imp, ['Age', 'Fare']),
    remainder='passthrough')

In [0]:
logreg = LogisticRegression(solver='liblinear', random_state=1)

In [0]:
pipe = make_pipeline(ct, logreg)
pipe.fit(X, y)
pipe.predict(X_new)

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

# Part 7 
Model Evaluation

In [0]:
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X, y, cv=5, scoring='accuracy').mean()
# does the data transformations after splitting, in order to avoid data-leakage 

0.8114619295712762

In [0]:
pipe.named_steps.keys()

dict_keys(['columntransformer', 'logisticregression'])

In [0]:
params = {}
params['logisticregression__penalty'] = ['l1', 'l2']
params['logisticregression__C'] = [0.1, 1, 10]
params

{'logisticregression__C': [0.1, 1, 10],
 'logisticregression__penalty': ['l1', 'l2']}

In [0]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy')
grid.fit(X, y);

In [0]:
results = pd.DataFrame(grid.cv_results_)
results 

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.020872      0.003060  ...        0.016946                6
1       0.019888      0.000348  ...        0.016258                5
2       0.023136      0.002266  ...        0.019787                2
3       0.020761      0.000376  ...        0.020141                3
4       0.029644      0.001220  ...        0.027533                1
5       0.023895      0.001830  ...        0.024080                4

[6 rows x 15 columns]

In [0]:
results.sort_values('rank_test_score')

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
4       0.029644      0.001220  ...        0.027533                1
2       0.023136      0.002266  ...        0.019787                2
3       0.020761      0.000376  ...        0.020141                3
5       0.023895      0.001830  ...        0.024080                4
1       0.019888      0.000348  ...        0.016258                5
0       0.020872      0.003060  ...        0.016946                6

[6 rows x 15 columns]

In [0]:
pipe.named_steps.columntransformer.named_transformers_

{'countvectorizer': CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                 dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                 lowercase=True, max_df=1.0, max_features=None, min_df=1,
                 ngram_range=(1, 1), preprocessor=None, stop_words=None,
                 strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                 tokenizer=None, vocabulary=None),
 'pipeline': Pipeline(memory=None,
          steps=[('simpleimputer',
                  SimpleImputer(add_indicator=False, copy=True,
                                fill_value='missing', missing_values=nan,
                                strategy='constant', verbose=0)),
                 ('onehotencoder',
                  OneHotEncoder(categories='auto', drop=None,
                                dtype=<class 'numpy.float64'>,
                                handle_unknown='error', sparse=True))],
          verbose=False),
 'remainder': 'passthrough'

In [0]:
params['columntransformer__pipeline__onehotencoder__drop'] = [None, 'first']
params['columntransformer__countvectorizer__ngram__range'] = [(1,1), (1,2)]
params['columntransformer__simpleimputer__add_indicator'] = [False, True]
params 
# We can name the pipelines to make this shorter, but in nested pipelines,
# its going to be chaos anyway 

{'columntransformer__countvectorizer__ngram__range': [(1, 1), (1, 2)],
 'columntransformer__pipeline__onehotencoder__drop': [None, 'first'],
 'columntransformer__simpleimputer__add_indicator': [False, True],
 'logisticregression__C': [0.1, 1, 10],
 'logisticregression__penalty': ['l1', 'l2']}

In [0]:
grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy')
grid.fit(X, y);

ValueError: ignored

In [0]:
grid.best_s

AttributeError: ignored

In [0]:
grid.predict(X_new)